name: 'Re-usable Docker Build Flow'
description: 'Used to setup and build a docker image for web client'

inputs:
  prefix:
    description: The assets prefix
    default: ""
  showdev:
    description: Including dev tools
    default: ""
  github-token:
    description: Github token
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install PNPM & Node
      uses: pocket/pocket-monorepo/.github/actions/install-pnpm-and-node@main
    - name: Generate release, if needed
      shell: bash
      run: HUSKY=0 pnpm dlx semantic-release
      env: 
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Check for new release
      shell: bash
      id: release-name
      run: |
        if [ -f ".version" ]; then
            echo "We have a semantic release"
        else
            echo 'No semantically releasable changes.'
            echo `git describe --abbrev=0 --tags` > .version
        fi
        release=$(cat .version)
        echo "RELEASE_VERSION=$release" >> $GITHUB_OUTPUT
    - name: Set version
      shell: bash
      run: |
        mkdir -p config
        echo "module.exports = '${{github.sha}}';" > ./config/version.js
    - name: Build
      shell: bash
      run: RELEASE_VERSION=${{steps.release-name.outputs.RELEASE_VERSION}} ASSET_PREFIX=${{inputs.prefix}} SHOW_DEV=${{inputs.showdev}} NODE_ENV=production pnpm run build