name: Pull Request
on:
    pull_request:

# TODO: change the github-actions branch to main once merged.
jobs:
    # lint all the files
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 
            - name: Install PNPM & Node
              uses: pocket/pocket-monorepo/.github/actions/install-pnpm-and-node@github-actions
            - name: Eslint
              run: pnpm lint
    # # unit test all the files~
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 
            - name: Install PNPM & Node
              uses: pocket/pocket-monorepo/.github/actions/install-pnpm-and-node@github-actions
            - name: Test
              run: pnpm test:ci
    # # we are building on branch to make sure there are no build errors
    # build:
    
    # web-build:

    # pocket-build:

    # pocket-infrastructure:

    # web-infrastructure: